version: 2.1

jobs:
  say-hello:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      - run:
          name: Generate config
          command: |
            chmod 555 ./.circleci/generate-config.sh
            ./.circleci/generate-config.sh | tee generated_config.yml
            echo 'dsdsDdsfsfsfsf'
workflows:
  say-hello-workflow: 
    jobs:
      - say-hello